spring:
  application:
    name: spring-boot-kafka
  kafka:
    # Kafka Broker 地址，可以设置多个
    bootstrap-servers:
      - 127.0.0.1:9092
    producer:
      #  0-不应答。1-leader 应答。all-所有 leader 和 follower 应答
      acks: all
      # 发送失败时，重试发送的次数
      retries: 3
      # 批量发送消息的最大数量
      batch-size: 16384
      # 批量发送消息的最大内存
      buffer-memory: 33554432
      # 消息key的序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息value的序列化
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          # 批处理延迟时间上限
          ms: 1000
    consumer:
      # 设置消费者分组最初的消费进度为 earliest 。可参考博客 https://blog.csdn.net/lishuangzhe7047/article/details/74530417 理解
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test
      properties:
        # 分区策略
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RangeAssignor

